### ISSUE TITLE
Fails to build for iOS with Carthage under Xcode 7.1

### ISSUE THREAD

**Issue by rpowelll** [Quick/Quick#410] opened 2015-10-25 22:46 UTC
I'm opening this as a separate issue to #406 as the build errors are distinct.

Currently Quick fails to build under Xcode 7.1 with the following entry in my _Cartfile_:

```
github "Quick/Quick" "xcode7.1"
```

Here's the output of running `carthage update` with this entry:

```
*** Building scheme "Quick-OSX" in Quick.xcworkspace
*** Building scheme "Quick-iOS" in Quick.xcworkspace
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
<module-includes>:1:1: warning: umbrella header for module 'Quick' does not include header '/Users/rpowell/Code/Nirvash/Carthage/Checkouts/Quick/Quick/DSL/QCKDSL.h'
<module-includes>:1:1: warning: umbrella header for module 'Quick' does not include header '/Users/rpowell/Code/Nirvash/Carthage/Checkouts/Quick/Quick/Configuration/QuickConfiguration.h'
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

**Comment by anandabits** [comment] 2015-10-26 21:13
Same issue here.  I see the following in the Carthage xcodebuild output log:

Build settings from command line:
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = appletvos9.0

=== BUILD TARGET Quick-iOS OF PROJECT Quick WITH CONFIGURATION Release ===

Check dependencies
target 'Quick-iOS' has bitcode disabled (ENABLE_BITCODE = NO), but it is required for the 'appletvos' platform

**Comment by anandabits** [comment] 2015-10-26 21:34
This appears to be caused by the SUPPORTED_PLATFORMS build setting.  When I change this back to iOS Carthage is able to build the xcode7.1 branch of Quick.

**Comment by rpowelll** [comment] 2015-10-26 22:27
It seems like we should have separate build targets for iOS and tvOS right? Why were they being combined in the first place?

**Comment by jeffh** [comment] 2015-10-27 05:27
They were merged because a contributor provided as a working implementation for tvOS. I haven't used it thoroughly, but it was working pre-xcode 7.1.

**Comment by jeffh** [comment] 2015-10-27 06:07
I've cut [v0.8.0](https://github.com/Quick/Quick/releases/tag/v0.8.0) which should solve tvOS issues (except for [tvOS + UI Testing Bundles](https://github.com/Quick/Quick/issues/413)).

**Closed by jeffh** 2015-10-27 06:07 UTC

**Comment by airshiplay** [comment] 2016-07-06 02:56
carthage update --platform iOS    target for Specific platform
