### ISSUE TITLE
UUID In Class Derived From Class Derived From QuickSpec Causes Crash Immediately On Starting Runtime

### ISSUE THREAD

**Issue by trevor-thoele** [Quick/Quick#894] opened 2019-05-31 16:31 UTC
### What did you do?

I placed a UUID variable in the public namespace of a class derived from a class that derived from QuickSpec.

This is enough to cause a crash immediately on starting the runtime:

```
import Quick

class Base : QuickSpec {}

class Tests : Base {
    var object = UUID()
}
```

I tried a few different objects here instead of the UUID (custom defined class, Int) along with access control differences and also if it was implicitly unwrapped or not. None of those seemed to change the outcome.

### What did you expect to happen?

The runtime to not crash.

### What actually happened instead?

The runtime crashes.

Sometimes I've seen `cyclic dependency metadata detected` related to this. Other times it appears to crash on `[QuickConfiguration initialize]` trying to push through `dispatch_once`.

### Environment

 - Quick: (2.0.0)
 - Nimble: (8.0.1)
 - Xcode Version: Version 10.2.1 (10E1001)
 - Swift Version: 5.0
 - Cocoapods: 1.5.3

**Comment by ikesyo** [comment] 2019-05-31 16:56
This is a duplicate of #853.

**Closed by ikesyo** 2019-05-31 16:56 UTC
