### ISSUE TITLE
Execution order issue with describe{} and and it{} blocks 

### ISSUE THREAD

**Issue by mark-anders** [Quick/Quick#426] opened 2015-11-21 12:18 UTC
(This is a pretty simple issue with a long winded explanation as to why I may be abusing the system)

I just ran into an odd issue with a test failing and it appears that the order of how `describe` blocks and their enclosed `it` blocks execute is not what I would expect.  Basically I had something that looks like:
```
class SyncSpec: QuickSpec {
    describe("Sync") {
        let account = Account.sharedAccount
        account.email = "me@a.com" 
        it("can sync") {
           expect(account.email).to(equal("me@a.com"))
        }
    }
}
class AccountSpec: QuickSpec {
    describe("Account") {
       it("can be reset") {
            let account = Account.sharedInstance
            account.email = "foo@bar.com"
           Account.resetSharedInstance()
           expect(account.email).to(beNil())
       }
    }
}

```
What I was seeing is a failure in `it("can sync")` in that account.email was nil.  Tracing through in the debugger, I watched the `describe("Sync")` account setup code execute followed by ` it("can be reset")` followed by `it("can sync")`.  I did not expect this.

Is this correct behavior?

I've never run into this before because I've never had code other than `it{}` and `describe{}` nested inside a `describe` block before. Maybe that is disallowed, though I haven't seen anything about it in the docs.

The reason I was trying this has to do with simply not understanding how shared examples are supposed to work, as I asked in issue #397.   Basically, for some parts of my code my tests are like this (pseudo-code):

```
it("can handle adds, updates and deletes") {
    var oc = ObjectContext()
    oc.add([obj1, obj2, ...., obj20])
   // do 10 different tests to make sure the context is as it should be.
   // update 3 objects
   // do the same 10 different tests to make sure the context is as it should be.
   // delete 3 objects
   // do the same 10 different tests ... blah blah blah
}
```
So, for the "do 10 different tests" step, I was attempting to move these into a sharedExample so that I could reuse the set of expectations repeatedly within the same "test".  This was not working and @jeffh told me to move my `itBehavesLike` block outside of the `it` block as nested examples are disallowed. 

This led me to wonder - if you can't have an `itBehavesLike` inside an `it` block, for a scenario like this, where does the code that does the add/update/delete operations live?  Maybe not in an `it` block.  I therefore thought that maybe the enclosing block was supposed to be a `describe` or `context` block, so that with the nested `it` and `itBehavesLike` to encapsulate the expectations, hence the code in the describe blocks.

It seems like this is not how I should do it. Is there a more correct way to structure what I'm trying to do?

**Comment by mutech** [comment] 2015-11-22 22:19
I had the same issue today and was similar to you surprised. If I understand correctly how Quick integrates into XCTest, the problem is that "it()" is what triggers the workflow (the test cases executed by XCTest). Code surrounding "it()" is evaluated lazily (not sure about that) and you can't make assumptions about the order in which contextual code is executed.

My strategy is now to always assign state that I want to test in expectations to constants (conceptually as part or prepare or execute phase of the test), then it doesn't matter if the state is changed between prepare/execute and the expectation. In my case I could also have used beforeEach, but I don't like the code duplication resulting from it when testing workflows (not sure if that's good practice though). In your case I would `let accountEmailAfterUpdate = account.email` and in "it()": `expect(accountEmailAfterUpdate).to(equal("me@a.com"))`. 

My first thought when encountering this issue was that this is crazy and just too complex. But after some more thinking I came to the conclusion that this problem is actually a feature because it pushes you more to comply to prepare/act/verify style specs, which is a good thing.

The advantage is that this decouples act phase from verification, so that you could (not should) just as well put all expectations in one it() clause or rearrange expectations in any way you like. For me that advantage justifies the extra typing.

**Comment by jeffh** [comment] 2015-11-23 05:11
Hey @mark-anders,

@mutech explained it well. I think a lot of clarity will come from explaining how Quick builds tests. Since it's based on XCTest, Quick needs to map it into methods (XCTest-style). Here's a short explanation on how Quick compiles tests into XCTest style:

- Quick *invokes* all blocks for `describe` and `context` to discover `it` closures.
- Quick then converts `it` into corresponding XCTest methods
  - The test method invokes all parent `beforeEach` methods
  - Then the method invokes the closure of `it` 
  - Finally, the test method invokes all `afterEach` methods.
- Quick gives XCTest these test methods as tests for XCTests to execute.

 This creates several implications to your issue:

- Use `beforeEach` for shared setup code ([documentation](https://github.com/Quick/Quick/blob/master/Documentation/QuickExamplesAndGroups.md#sharing-setupteardown-code-using-beforeeach-and-aftereach)). Don't put it inside the `describe` or `context` blocks directly. You can declare variables inside `describe` and `context` as needed.
- Because there's a "compiling" step that Quick does in order to determine what method to run, you're seeing the execution order you're expecting. The actual test execution (`it` closures) are dependent to the implementation of XCTest. In short, it's correct behavior

Shared examples are solving the problem of repeated expectations (aka, identical `it` closures). A perfect use case is if you're testing implementations of a protocol. A shared example can describe behavior an implementation of a protocol should conform to.

Using nesting of `context` and `describe` closures with `beforeEach` gives you the shared setup that you wish to have:

```swift
var oc: ObjectContext!
describe("persistence") {
    context("with objects already in the context") {
        beforeEach {
            oc = ObjectContext()
            oc.add([obj1])
        }

        it("allows fetching previously stored objects") {
           expect(oc.objects()).to(equal([obj1])
        }

       describe("deleting an object") {
           beforeEach {
               oc.delete(obj1)
           }

           it("no longer retrieves the deleted object") {
              expect(oc.objects()).to(beEmpty())
           }
       }
    }
}
```

In BDD-styled testing, it's commonly recommended to limit your `it` closures to only perform assertions -- usually only one per closure.

**Comment by istx25** [comment] 2016-08-10 20:20
This question was answered by @mutech and @jeffh. Closing issue. Feel free to reopen if necessary.

**Closed by istx25** 2016-08-10 20:20 UTC
Labels: question

**Comment by vinamelody** [comment] 2016-11-15 08:18
@jeffh the documentation link now points to [this page](https://github.com/Quick/Quick/blob/master/Documentation/en-us/QuickExamplesAndGroups.md) :)
