### ISSUE TITLE
Quick tests run but console says no tests were executed

### ISSUE THREAD

**Issue by JohnTheBastard** [Quick/Quick#750] opened 2017-10-05 22:20 UTC
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I ran all tests (⌘U) in Xcode 9.1 Beta

### What did you expect to happen?

I will preface by saying this is my first time using Quick/Nimble. I haven't seen correct console output to compare to.

I expected to see an accurate summary of my tests in the console.

### What actually happened instead?

The console reports that none of the Quick tests were executed.

### Environment

List the software versions you're using:

 - Quick: *1.2.0*
 - Nimble: *7.0.2*
 - Xcode Version: *9.1 Beta (9B37)* 
 - Swift Version: *4.0*

Please also mention which package manager you used and its version. Delete the
other package managers in this list:
 - Carthage: *0.25.0*

### Project that demonstrates the issue

The project in question is private. I will try to repro in another repository this weekend.

![quicktests](https://user-images.githubusercontent.com/4441293/31255192-6f9eb744-a9e0-11e7-9842-9392da74752c.png)

**Comment by ikesyo** [comment] 2018-07-12 16:13
I think that is just an implementation limitation and should be safely ignored. You should see the next line. Closing.

**Closed by ikesyo** 2018-07-12 16:13 UTC

**Comment by ikesyo** [comment] 2018-07-12 16:39
This was a duplicate of #177.
