### ISSUE TITLE
Test Suite 'Quick.framework' appears in xcodebuild output

### ISSUE THREAD

**Issue by paulyoung** [Quick/Quick#177] opened 2014-10-30 15:00 UTC
When running `xcodebuild -workspace Engine.xcworkspace -scheme Engine-iOS -sdk iphonesimulator8.0 clean test` the output ends with the following:

``` sh
Test Suite 'All tests' started at 2014-10-30 01:34:19 +0000
Test Suite 'Engine-iOSTests.xctest' started at 2014-10-30 01:34:19 +0000
Test Suite 'EngineSpec' started at 2014-10-30 01:34:19 +0000
Test Case '-[EngineSpec root_example_group__engine__tests_should_run]' started.
Test Case '-[EngineSpec root_example_group__engine__tests_should_run]' passed (0.139 seconds).
Test Suite 'EngineSpec' passed at 2014-10-30 01:34:19 +0000.
     Executed 1 test, with 0 failures (0 unexpected) in 0.139 (0.144) seconds
Test Suite 'Engine-iOSTests.xctest' passed at 2014-10-30 01:34:19 +0000.
     Executed 1 test, with 0 failures (0 unexpected) in 0.139 (0.153) seconds
Test Suite 'Quick.framework' started at 2014-10-30 01:34:19 +0000
Test Suite 'Quick.framework' passed at 2014-10-30 01:34:19 +0000.
     Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.036) seconds
Test Suite 'All tests' passed at 2014-10-30 01:34:19 +0000.
     Executed 1 test, with 0 failures (0 unexpected) in 0.139 (0.203) seconds
** TEST SUCCEEDED **
```

The part I don't understand is this:

``` sh
Test Suite 'Quick.framework' started at 2014-10-30 01:34:19 +0000
Test Suite 'Quick.framework' passed at 2014-10-30 01:34:19 +0000.
     Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.036) seconds
```

While this isn't causing any problems for me I'd prefer to understand why that is appearing there.

**Comment by istx25** [comment] 2016-10-28 19:48
I haven't seen this behaviour in a long time. Is it safe to say it has been fixed 2yrs later?

**Comment by jeffh** [comment] 2016-11-08 07:15
Nope, it's still there:

![screen shot 2016-11-07 at 11 12 25 pm](https://cloud.githubusercontent.com/assets/68616/20090061/b0fe07c2-a53f-11e6-8fcd-bfdde22757ee.png)

```
Xcode 8.1 (8B62)
Quick 0.10.0
```

Creating a new project that links with Quick will make it show up.

**Comment by istx25** [comment] 2016-11-08 07:56
Strange. I didn't see that when I tried before. I'll try to reproduce it again. :)

**Comment by istx25** [comment] 2016-12-31 02:07
I've been able to reproduce the problem. Also looked through the logs that I mentioned before and the problem was there; was just looking in the wrong area.

**Comment by ikesyo** [comment] 2020-09-19 15:31
My understanding is: Qiuck.framework contsins QuickSpec class which extends XCTestCase class, so XCTest runtime asuumes the framework target is a test suite. I think there is no way to suppress this behavior. Closing.

**Closed by ikesyo** 2020-09-19 15:31 UTC
Labels: bug, help wanted
