### ISSUE TITLE
Issue with running single Swift test case

### ISSUE THREAD

**Issue by hirad** [Quick/Quick#502] opened 2016-03-22 23:53 UTC
Hi guys,

I'm getting started with Quick and testing in Swift, and I'm hitting some strange issues with Xcode 7.3. 

I wrote one Swift test case in Quick that's running just fine - it gets picked up by Xcode and runs every time I run my tests. It also runs individually if I run it that way. 

Then I added a second test case, and hit the strange issues.
a) It does not show up under the tests navigator (see attached),
b) When I run it individually, the *first test* case that I wrote runs first, and then the second one runs, 
c) The second test case fails (I get the "Tests Failed" message from Xcode) but nothing is logged either in the console outputs or in the UI (red highlights on expectations). In fact, I'm pretty sure the test should be passing.

This looks like an Xcode bug, but I'm wondering if there are any workarounds on this (I did not find much). 

![screen shot](https://cloud.githubusercontent.com/assets/1005340/13971554/5492f318-f04e-11e5-8709-1ec228c0c731.png)

**Comment by modocache** [comment] 2016-04-30 20:03
If you use Specta or Quick and are disappointed with tests disappearing in Xcode's Test Navigator, tests lingering in the Test Navigator despite no longer being defined, or even tests not being run, please read and duplicate this radar: https://openradar.appspot.com/26028557.

Xcode does not provide the Specta or Quick maintainers with an API to address these problems. The best way to contribute to fixing these issues is to communicate to the Apple XCTest team that this is a use case we wish they'd support better. The best way I know to do that is to ask you all to re-submit https://openradar.appspot.com/26028557. 🙇 

Closing this, since this is a duplicate of https://github.com/Quick/Quick/issues/221.

**Closed by modocache** 2016-04-30 20:03 UTC
