### ISSUE TITLE
Package file specifies incorrect macOS version

### ISSUE THREAD

**Issue by danielsaidi** [Quick/Quick#1007] opened 2020-08-31 18:48 UTC
[ x] I have read CONTRIBUTING and have done my best to follow them.

## What did you do?

Opened a project that requires Nimble in Xcode 12 and tried to build it.

## What did you expect to happen?

The project should build.

## What actually happened instead?

The project doesn't build due to a Nimble build error.

## Environment

List the software versions you're using:

* Quick: 3.0.0
* Nimble: 8.1.1
* Xcode Version: 12 beta
* Swift Version: 5.3

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

* Swift Package Manager 5.3.0 (swiftpm-5.3.0)

## Solution

The Package file specifies

```
platforms: [
    .macOS(.v10_10), .iOS(.v8), .tvOS(.v9)
],
```

but `recordFailure` is only available in 10.13 or newer.

I guess the package files should be updated to reflect this properly.

![](https://user-images.githubusercontent.com/429927/91754809-54644500-ebca-11ea-8fd3-eb94db9239e9.png)

**Comment by ikesyo** [comment] 2020-09-01 01:27
Duplicate of #995.

**Closed by ikesyo** 2020-09-01 01:27 UTC
