### ISSUE TITLE
Xcode crash: "Global is external, but doesn't have external or weak linkage!"

### ISSUE THREAD

**Issue by nikita-leonov** [Quick/Quick#354] opened 2015-07-26 18:27 UTC
I have Xcode crashing during compilation on a following code snippet:

```
                it("it should signal a name of peripheral") {
                    waitUntil{ completed in
                        delegate.didUpdateName.observe(next: { name in
                            completed()
                        })
                    }
                }
```

with an error:

```
Global is external, but doesn't have external or weak linkage!
i8* ()* @_TFFFFFFC20ReactiveBluetooth_Tests30ReactivePeripheralDelegateSpec4specFS0_FT_T_U_FT_T_U1_FT_T_U0_FT_T_U_FFT_T_T_auL_9completedFT_T_
invalid linkage type for function declaration
i8* ()* @_TFFFFFFC20ReactiveBluetooth_Tests30ReactivePeripheralDelegateSpec4specFS0_FT_T_U_FT_T_U1_FT_T_U0_FT_T_U_FFT_T_T_auL_9completedFT_T_
LLVM ERROR: Broken module found, compilation aborted!
```

When completed is commented out, it compiles well. It happens on Xcode version 6.4 (6E35b). On a previous versions of Xcode similar code snippets were working fine. Any ideas what could be a workaround?

**Comment by nikita-leonov** [comment] 2015-07-26 18:39
I found one workaround by redefining completed locally as follows: 
it("it should signal a name of peripheral") {
                    waitUntil{ completed in
                        let completed = completed
                        delegate.didUpdateName.observe(next: { name in
                            completed()
                        })
                    }
                }

Does not looks elegant, but it works.

**Comment by jeffh** [comment] 2015-07-27 04:47
Hey @nikita-leonov,

Strange bug indeed. Your fix looks suspiciously like a lexical closure bug which is potentially a radar to file. Do you have a sample project that potentially reproduces this?

Thanks,
Jeff

**Comment by nikita-leonov** [comment] 2015-07-27 07:56
@jeffh Yes, I created a sample how to reproduce an issue. https://github.com/nikita-leonov/nested-closures-xcode-crash I also found a bunch of other similar reports in ReactiveCocoa repository. I am not sure about Radar existence yet, so will create a new Apple issue tomorrow for it.

**Comment by nikita-leonov** [comment] 2015-07-27 16:42
@jeffh I reported it to apple and into open radar — https://openradar.appspot.com/radar?id=5066837008056320
What should we do with this ticket? It is something that should appear for Quick users really often, as there are a lot of closures nesting. Also in Swift 1.2 it is reproducible all the time.

**Comment by jeffh** [comment] 2015-08-02 06:34
Thanks @nikita-leonov, I've marked it as blocked, if the radar gets fixed, then I'll close it.

**Comment by istx25** [comment] 2016-10-28 20:42
I noticed that the radar is still open but I think we should close this anyways. The problem is documented here for any others who find this and Apple could take a million years if they so desired. Closing for now. Feel free to reopen if necessary.

**Closed by istx25** 2016-10-28 20:42 UTC
Labels: blocked, bug, tricky
