### ISSUE TITLE
Quick does not work well with the Xcode 9 test runner

### ISSUE THREAD

**Issue by ratkins** [Quick/Quick#745] opened 2017-09-20 08:39 UTC
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Run all tests (⌘U) from Xcode 9.

### What did you expect to happen?

Quick Specs should have a green (for passing) or red (for failing) glyph in the left hand gutter of Xcode's editor windows, like they did in Xcode 8 and earlier. Ideally, one per `it()`, `describe()` and `context()` block, but I'd take one at the top level `spec()` as a good start. I should be able to click on these to (re-)run the individual block.

Also, the test navigator does not consistently show the list of specs correctly. Sometimes they're all there, sometimes they're not, sometimes they're there but ghosted. This seems to work well for plain XCTests.

### What actually happened instead?

No glyphs are evident. All you get is a red X glyph on a failed test. Test Navigator does not always show a complete and correct list of the available specs.

### Environment

List the software versions you're using:

 - Quick: 1.1.0
 - Nimble: 7.0.1
 - Xcode Version: Version 9.0 (9A235)
 - Swift Version: 4.0

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Carthage: 0.25.0 

Note: `fit()` and `fdescribe()` are inconvenient stopgap measures at best. I have a nice IDE in front of me and I'd like to use it!

I realize this may be more of an issue of the hooks Xcode makes available for Quick to integrate with and what I want may not be possible right now, but I'd like to have this issue here to link the radar to if this is the case.

**Comment by gperdomor** [comment] 2017-09-21 01:25
maybe related to #744 ?

**Comment by mosamer** [comment] 2017-09-25 10:31
This is probably related to #219

**Comment by ngutman** [comment] 2017-10-03 09:00
Got the same issue, for me even after running the tests non of the Quick generated tests show up in the navigator.

I managed to get it to be a bit more usable in Xcode 9 by adding a dummy test method to my Quick specs, afterwards I can at least run a specific file which is better than having to run the entire test suite...

````swift
class MyTest: QuickSpec {
    override func spec() {
        describe("raw segment recorder") {
         ....
        }
    }
    
    public func testDummy() {}
}

**Comment by ratkins** [comment] 2017-10-05 11:47
This is a neat trick @ngutman and now I can run the tests from the icons in the editor gutters, but when my tests pass I get a green diamond with a "-" in it, rather than a green diamond with a tick 😞. Putting in a `XCTestAssertTrue(true)` as a body in my dummy test doesn't even seem to help.

**Comment by drekka** [comment] 2017-10-16 03:25
Confirmed here on Xcode 9GM. Unless there is at least one `func test...() {}` XCTest then Quick test files will not appear in the test navigator at all.  Even after adding a funny test method, I had to clear derived data and restart Xcode to get them to appear.

**Comment by farshadtx** [comment] 2017-11-21 02:52
+1

**Comment by drekka** [comment] 2017-11-23 00:43
This seems to now be working fine in Xcode GM 9.1 so no need to add the dummy tests.

**Comment by hermanccw** [comment] 2018-01-08 05:51
This seems to be broken again on Xcode 9.2 (9C40b)

**Comment by Prince2k3** [comment] 2018-02-01 05:48
This is broken on Xcode 9.2.1 too. I just started getting into Quick and nothing seems to be working like the tutorials and GitHub page says it should. The test don't appear in the sidebar, beforeSuite never called and running it always says test succeeded.

**Comment by drekka** [comment] 2018-02-01 23:19
Working fine here on Version 9.2 (9C40b)

**Comment by Prince2k3** [comment] 2018-02-01 23:33
I eventually got it to work. I literally had to remove everything and do it all over again to make it work! Just happy to be testing with Quick!

**Comment by GregoryMaks** [comment] 2018-02-14 11:14
Same issue on Version 9.2 (9C40b), sometimes restart does help. Also running one specific test file works fine. ⌘U just ignores most of Quick tests.

**Comment by ikesyo** [comment] 2018-09-21 15:44
Closing this as the reported issue, how to reproduce, and so on are unclear.

**Closed by ikesyo** 2018-09-21 15:44 UTC

**Comment by KrishnaChaitanyaAmjuri** [comment] 2019-11-13 18:39
The same issue is happening in XCode 11.2. Also, tests aren't even running

**Comment by ratkins** [comment] 2021-02-04 10:50
Xcode 12.4 also. It looks like this is really being tracked in #219 and [this openradar](https://openradar.appspot.com/26028557).
