### ISSUE TITLE
It methods not getting called and test suite shows all passes with null for name

### ISSUE THREAD

**Issue by marlowcharite** [Quick/Quick#363] opened 2015-08-18 04:14 UTC
I'm having this weird issue that I don't see any one else has logged so wondering if it's something I'm doing wrong. I can get my tests to properly run once or twice but after that I get nothing where the assertions aren't evaluated and no it blocks are ran. Instead I get the notification that all my tests have passed:

``` shell

Test Suite 'Selected tests' started at 2015-08-18 00:07:14.078
Test Suite 'RealmManagerSpec' started at 2015-08-18 00:07:14.079
Test Case '-[HoodwinkedTests.RealmManagerSpec (null)]' started.
Test Case '-[HoodwinkedTests.RealmManagerSpec (null)]' passed (0.004 seconds).
Test Suite 'RealmManagerSpec' passed at 2015-08-18 00:07:14.084.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.004 (0.005) seconds
Test Suite 'Selected tests' passed at 2015-08-18 00:07:14.086.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.004 (0.008) seconds
``` 

and I have my spec setup like so:

``` swift

class RealmManagerSpec: QuickSpec {
    
    override func spec() {
        
        describe(".persist(_:_)") {
            
            context("successfully imports into realm") {
                
                let resourcePath = NSBundle(forClass: RealmManagerSpec.self).resourcePath!
                let realmPathForTesting = "\(resourcePath)/realm.test"
                
                var realm: Realm!
                
                beforeEach {
                    
                    self.deleteRealmAtFilePath(realmPathForTesting)
                    realm = try! Realm(path: realmPathForTesting)
                }
                
                
                afterEach {
                    
                    self.deleteRealmAtFilePath(realmPathForTesting)
                    
                }
                
                it("creates and persists tracks") {
                    
                    expect(realm.objects(Track).count).to(equal(0))
                    
                    let tracks = DHJSONParser.convertJSONToTracks(self.jsonFromFile("testTracks"))
                    RealmManager.persist(tracks, intoRealm: realm)
                    
                    expect(realm.objects(Track).count).to(equal(10))
                    
                }

                it("creates and persists videos") {
                    
                }
                
            }
            
        }

    }
    
    func deleteRealmAtFilePath(path: String) {
        
        let fileManager = NSFileManager.defaultManager()
        try! fileManager.removeItemAtPath(path)
        let lockPath = path + ".lock"
        try! fileManager.removeItemAtPath(lockPath)
    }
    
    func jsonFromFile(fileName: String) -> [JSON] {
        
        let path = NSBundle(forClass: RealmManagerSpec.self).pathForResource(fileName, ofType: "json")!
        let jsonData = NSData(contentsOfFile: path)!
        let json = try! NSJSONSerialization.JSONObjectWithData(jsonData, options: .MutableContainers)
        return decode(json)!
    }
    
}
```

*Update: seems like the issue only occurs when using the navigation menu to run tests, I don't have any issues using `command+U`*

**Comment by mkauppila** [comment] 2015-08-18 14:23
To me this looks like an Xcode issue instead of being an actual bug with Quick. Which Xcode version are you currenly using?

**Comment by marlowcharite** [comment] 2015-08-18 14:37
@mkauppila latest beta. I was more wondering if anyone else experiences this or not. I'm find using the keys to running my test as that is my natural workflow anyway

**Comment by mkauppila** [comment] 2015-08-18 17:21
I was intrigued enough to try to reproduce this issue. No luck though. I tried running test using `Product -> Test` and also by `command+U` multiple times without noticeable difference in the output.

**Comment by marlowcharite** [comment] 2015-08-18 18:02
Try it through the side menu navigator on the left hand side. Every time I run it through there is when I get the issue. @mkauppila

**Comment by mkauppila** [comment] 2015-08-18 18:39
Thanks for the tip :+1: Now I got this reproduced. What a weird issue! Especially concerning that the issue only occurs when running the specs from the side bar. And somehow the name of the `it` blocks become  `(null)`. Even though, `XCTestCase`s seems to run just fine, I'd still suspect that this is a regression in the latest Xcode beta. Could be worth filing a radar to Apple :bug:

**Comment by mkauppila** [comment] 2015-08-24 16:53
I'll close the issue since this is (mostly likely) an Xcode bug. Let's reopen this if the problem is present also in the stable version of Xcode :smiley:

**Closed by mkauppila** 2015-08-24 16:53 UTC
