### ISSUE TITLE
No such module 'Quick' in Xcode 8.3.3

### ISSUE THREAD

**Issue by jkunzelman** [Quick/Quick#715] opened 2017-06-26 17:48 UTC
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Trying to install quick in objective c/swift project with cocoa pods gives me the error "No such module 'Quick'

### What did you expect to happen?

project should build successfully and run tests.

### What actually happened instead?
unable to run build/test

### Environment

List the software versions you're using:

 - Quick: 1.1.0
 - Nimble: 7.0.1
 - Xcode Version: 8.3.3 (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version:  (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: 1.0.1 (Use `pod --version` in Terminal)

**Comment by ikesyo** [comment] 2017-06-26 22:44
Please update CocoaPods and that should fix this.

**Comment by ikesyo** [comment] 2017-06-26 22:46
Closing as a duplicate of #706.

**Closed by ikesyo** 2017-06-26 22:46 UTC

**Comment by jkunzelman** [comment] 2017-06-28 15:43
confirmed this was the issue.

**Comment by ondev** [comment] 2017-08-04 07:32
I have the same issue. 
xcode 8.3.3 
cocoapods 1.2.1
Quick and Nimble are latest

**Comment by BumwooPark** [comment] 2017-08-18 05:19
same issue too
