### ISSUE TITLE
Unit tests aren't recognized by AppCode 3.3

### ISSUE THREAD

**Issue by shineycode** [Quick/Quick#421] opened 2015-11-10 05:24 UTC
Unit tests that inherit from XCTestCase are recognized by AppCode as runnable but none of the Quick tests are recognized.

**Comment by jeffh** [comment] 2015-11-10 06:00
Hey @shineycode,

I don't know much about AppCode's internals to how they intepret specs. And I don't actively use AppCode a lot. It might be worth filing an issue with them to see if they'll support Quick! ;)

**Comment by mark-anders** [comment] 2015-11-10 10:55
Hi @shineycode, I'm using Quick with AppCode 3.3 and am able to run all of my tests via a run configuration and they work and all show up in the test runner window. I should note that I'm still using it with XCode 7.01. There are some things that don't work properly (I think) such as if I click on a test, nothing happens, but if I click on the class, I can jump to the source and the output is shown.  I can click on the output and jump to any errors.

Can you not get this far?

**Comment by shineycode** [comment] 2015-11-11 05:27
@mark-anders I'm using Appcode 3.3 with Xcode 7.1.

Here's how the XCTestCase derived tests appear:
<img width="405" alt="xctest-derived" src="https://cloud.githubusercontent.com/assets/1053560/11084550/92f24cd2-87f1-11e5-8a4f-1aad2f2fd32a.png">

And here's how the Quick derived tests appear:
<img width="473" alt="quick-derived" src="https://cloud.githubusercontent.com/assets/1053560/11084551/97ac0d26-87f1-11e5-9701-9ce6b8e0b2bd.png">

@jeffh Because the XCTestCase version show up in AppCode and I'm able to run them, I figured I'd post here first. I'm not sure if the Jetbrain folks will want to support every unit test library out there.

**Comment by mark-anders** [comment] 2015-11-11 16:27
@shineycode - I'm seeing the same thing with AppCode 3.3.1 (just came out today) and  XCode 7.0.  It seems like the testing support is even a bit more broken than what you're seeing though.  I created a new XCTest file in my project which has all other tests based on Quick.  If I right click on the XCTest file, I see the run commands as per your first image, while I don't when I do the same for the Quick based ones.  So clearly there's something wrong.  However, if I attempt actually run the tests from right clicking on the XCTest file, what actually runs is the Quick based ones!

So it seems like there are a variety of bugs re: Unit Testing and they're not just about Quick.

However, I don't run my tests via the right click method and this may work for you.  Create a custom Run/Debug configuration for your tests.  You should be able to run those by switching to use that.

Final note:  I cannot for the life of me get the XCTest based file to run in AppCode, even after creating a custom Run config that targets that class and the single testExample() function it contains.  What I get is that all of my Quick based tests run.  So it seems like AppCode has some serious testing issues.  Not sure when this happened as my old test configs work fine.  I'll file some bugs!

**Comment by mark-anders** [comment] 2015-11-17 20:10
Just a followup.  I filed a few bugs with AppCode for this and after going back and forth, there are definitely issues with Quick in AppCode that don't appear for vanilla XCTest based ones.  A developer has been looking into it and having followup questions, so hopefully it will be addressed in the near future.

**Comment by modocache** [comment] 2015-11-17 20:28
Awesome, thanks for speaking to the AppCode folks! Would love to see this
supported.

I'm aware AppCode added support for Kiwi a while back:
https://github.com/kiwi-bdd/Kiwi/issues/306#issuecomment-37565971

I'm not sure, but I assume that it should support Specta, Quick, and pretty
much any other framework. Since AppCode is a closed-source tool, I guess we
can't know how easy or hard that would be.

**Comment by mark-anders** [comment] 2015-11-17 21:31
While I haven't used it recently, I just checked how well Specta works using one of my old projects and it seems to work fine. I'm not sure if you've used AppCode or other JetBrains tools much, but they do a phenomenal job of understanding and manipulating code.  It's why you can do tons of refactoring for Swift today while XCode still doesn't do any.  

As such, they're building up the code model to work from themselves and they're still not quite there.  One thing to point out is that though AppCode seems to be closed source only, JetBrains open sources a LOT of their stuff and there are open source, community editions of a number of their tools.  So if you wanted to see how they handle code in general, I think you could learn a bunch from the OS versions.

One thing that is probably a complicating factor for Quick and why it doesn't just work is that Quick is a mixed language framework and (I think) the main class that they'd need to understand, QuickSpec, is implemented in Obj-C.  When I'm editing one of my tests and attempt to navigate to QuickSpec, it says it can't find it.  Yet, if I do the same for AlamoFire, another Cocoapod integrated framework, it works fine.  

Looking just at the Quick code project, if I open `FunctionalTests_SharedExamplesTests_SharedExamples`, I can cmd-click on `Configuration` and navigate ok, while `QuickConfiguration` can't be found.  So I think that's a factor.

They seem to be on it, though, so I'm hopeful.

Here's a bug where some of the discussion is taking place.  I'm going to update it with some of this content (which I just figured out while editing this comment).

https://youtrack.jetbrains.com/issue/OC-12719

**Comment by marlowcharite** [comment] 2015-12-11 12:29
Does anyone have an update on this? I've been searching around and haven't seen a fix or anything. Thanks

**Comment by JeffBNimble** [comment] 2016-02-13 13:51
I too have been interacting with the AppCode team for support to run Quick tests. There is an existing feature request and it would greatly help if everyone would go vote for it .

https://youtrack.jetbrains.com/issue/OC-11661

I can get Quick tests to run in AppCode if I create my own Run Configuration using a Pattern. The problem is that the pattern itself is ignored and it runs ALL tests.

Consequently, I authored two bugs against AppCode:
* https://youtrack.jetbrains.com/issue/OC-13136
* https://youtrack.jetbrains.com/issue/OC-13137

Both were immediately closed as duplicates of the feature request. If you look at the comments on the feature request and the two bugs I filed, you'll get more context.

I know the AppCode team is really busy trying to build in much better support for all Swift language features. I would hope lots of votes for Quick support would get that feature on their radar, so go vote!!!

**Comment by marlowcharite** [comment] 2016-02-13 14:27
I just want to let everyone know that Quick unit tests work in the latest AppCode 3.4 EAP

**Comment by JeffBNimble** [comment] 2016-02-13 14:49
I am running AppCode 3.4 EAP and not seeing the ability to run Quick tests. I am able to get them to run as described in my previous post, but right-clicking on the test does not present a Run... option and using a custom Run Configuration identifying the Quick Test class doesn't work.

@marlowcharite Can you elaborate on what you're seeing with AppCode 3.4 EAP? Hopefully, I'm just missing something.

**Comment by marlowcharite** [comment] 2016-02-13 14:52
@JeffBNimble ahhhh. No you're right I can't run through right-clicking I can just run the entire suite.

**Comment by JeffBNimble** [comment] 2016-02-13 14:58
@marlowcharite ok :(, I was hoping you found some workaround. At least we can run them, just not ideally. Thanks for checking.

**Comment by istx25** [comment] 2016-08-10 20:25
Since this issue has to do with AppCode (and not Quick - from what I can see), I am going to close this issue for now. If I missed anything, please feel free to reopen it. Feel free to upvote the support for Quick using the link @JeffBNimble shared above.

**Closed by istx25** 2016-08-10 20:25 UTC
Labels: enhancement, help wanted

**Comment by modocache** [comment] 2016-08-11 13:44
Sounds good, thanks @istx25!

Plus, I think we all know open-source software is the future anyway. Instead of worrying about AppCode, it'd be awesome to see some [Visual Studio Code](https://code.visualstudio.com/) or [Nuclide](https://github.com/facebook/nuclide) packages that support XCTest and Quick. 😎

**Comment by istx25** [comment] 2016-08-11 15:20
I will keep that in mind. Possibly some good items for our roadmap (which we'll be writing soon enough).

**Comment by anton-matosov** [comment] 2017-10-15 20:32
I have just discovered that https://youtrack.jetbrains.com/issue/OC-11661 "Add support for testing with Quick" is currently **IN PROGRESS** since October 10, 2017!! Lets hope AppCode team is going to release this long awaited feature soon!
They have recently release support for Catch tests (C++ BDD) so it looks like they are actively catching up on the good support for test frameworks.
