### ISSUE TITLE
Xcode 7.3 support

### ISSUE THREAD

**Issue by raven** [Quick/Quick#494] opened 2016-03-01 21:48 UTC
I see [this revert](https://github.com/Quick/Quick/commit/bc67084995ba3c27a52cf19036f9585f09cc48f1) https://github.com/Quick/Quick/commit/bc67084995ba3c27a52cf19036f9585f09cc48f1 for updating to the latest Nimble, however I can't find any further reasons as to why it failed and was reverted. I also can't find an associated issue on the Nimble project. What can I do to help?

**Comment by briancroom** [comment] 2016-03-02 04:38
Thanks for raising this again @raven. I opened https://github.com/Quick/Quick/pull/486 a couple of weeks ago with the necessary changes to allow using the newer Nimble versions and still have a functional test suite for Quick. It's been pretty quiet around that PR so I'd welcome any feedback! I realize that the changes introduced there aren't the most pleasant...

**Comment by briancroom** [comment] 2016-03-02 12:20
@ravan Can you check if things seem to be working for you now that #486 has been merged?

**Comment by raven** [comment] 2016-03-02 21:41
I have since updated both Quick and Nimble to latest commits on master for both, and our project is reporting number of tests 0, failures 0 when run via fastlane's scan

```
+--------------------+-------+
|        Test Results        |
+--------------------+-------+
| Number of tests    | 0     |
| Number of failures | 0     |
+--------------------+-------+
```

Also running the unit tests straight from within Xcode does appear to be running the tests(seen from the Test navigator), but the console output doesn't report any success or failure, or any mention of individual tests passing / failing.

Now our project has a bunch of moving parts, and updating Quick/Nimble was the first thing to bite off after updating to Xcode7.3 so I'll try and spend some time to discern what is failing where and report back.

**Comment by gapl** [comment] 2016-03-23 08:55
@raven Have you figured out how to solve this issue? We are also experiencing this issue now.

**Comment by paweldudek** [comment] 2016-03-23 10:15
Same issue here. @raven the problem with `scan` is that it uses `xcpretty` under the hood. `xcpretty` parses XCTest output to determine what test succeeded/failed. Since there's no output from XCTest right now the tool itself is broken. 

The fix would be to restore output or find a way to let `xcpretty` know about test successes/failures, however I'm not skilled enough with XCTest to know/propose a solution.

**Comment by raven** [comment] 2016-03-23 10:21
Havent looked at this recently. But it was observable outside of using scan / xcpretty. Just a straight up cmd+u from within Xcode only put some basic logs into the console and then 0 tests. Im away from the project until tomorrow, Il provide more info then. 

Get Outlook




On Wed, Mar 23, 2016 at 3:15 AM -0700, "Pawel Dudek" <notifications@github.com> wrote:












Same issue here. @raven the problem with scan is that it uses xcpretty under the hood. xcpretty parses XCTest output to determine what test succeeded/failed. Since there's no output from XCTest right now the tool itself is broken. 



The fix would be to restore output or find a way to let xcpretty know about test successes/failures, however I'm not skilled enough with XCTest to know/propose a solution.

**Comment by paweldudek** [comment] 2016-03-23 10:27
@raven oh yeah, the problem is that Apple changed XCTest with Xcode 7.3 so that it no longer prints log onto console, meaning it cannot be parsed by `xcpretty`. A crude solution would be to add a `XCTestObservation` object that mimics original XCTest output so that `xcpretty` can pick it up.

**Comment by ashfurrow** [comment] 2016-03-24 20:27
> the problem is that Apple changed XCTest with Xcode 7.3 so that it no longer prints log onto console

Thanks for clarifying this – seems like a pretty big change, yet I can't find it in the Xcode release notes. Could anyone point me in the direction of a setting or workaround to re-enable this? We have two tools that – like xcpretty – rely on this output, and they no longer work.

**Comment by paweldudek** [comment] 2016-03-24 21:07
So I did a bit more of digging and it seems that latest XCTest didn't alter this behaviour. Well, not entirely.

I've started by checking out what happens when I create a vanilla project in Swift. I've used basic Xcode template with tests in Swift. Running tests gets the longs onto console.

Then I've checked what happened to another RSpec-style BDD framework from Objective-C world - Specta. I've used one of the projects that I'm working on and everything is fine there - logs are printed onto console. 

It looks like there's something in Quick that, when run under latest Xcode, prevents those logs from being printed onto console. I'm doing a bit more digging into this right now.

**Comment by paweldudek** [comment] 2016-03-24 21:12
Got it. 

Just as I suspected the issue lies in Nimble and `CurrentTestCaseTracker`. Looks like adding custom observer prevents defaults output from being printed onto console. I haven't found any trace of such behaviour being mentioned in docs - this should just work. Could this be a bug in latest XCTest?

**Comment by ashfurrow** [comment] 2016-03-24 21:19
Ah, interesting! We use Specta and Quick for our tests, makes sense if Nimble is causing the console printing to no longer work that it might affect the Specta tests, too. Thanks for looking into it!

**Comment by ashfurrow** [comment] 2016-03-25 00:16
@paweldudek has opened a PR to fix this in Nimble here: https://github.com/Quick/Nimble/pull/271

**Comment by phatblat** [comment] 2016-04-09 23:02
@raven Can you test out the latest Quick from master? I expect this issue to be resolved but it'd be nice to hear if it's working for you before we cut a release.

**Comment by waterlink** [comment] 2016-04-10 00:26
I am not sure if it is related: for me on XCode 7.3 last `it` (project-wide) is not run. Upgrading to `Quick` master does not help.

**Comment by humblehacker** [comment] 2016-04-17 16:07
I'm using the latest Quick from master, and I still have this problem, though it's much less frequent.  It occurs mainly when I turn off all but a single spec (using the Test action in the scheme). If I turn on all the tests, the problem goes away.

**Comment by briancroom** [comment] 2016-04-21 02:15
@humblehacker That sounds like a pretty interesting issue, but I haven't been able to reproduce it, unfortunately. If you could reduce a minimal sample where you're observing it and open a separate issue that would be 💯

**Comment by istx25** [comment] 2016-08-10 19:46
What's the status on this?

**Comment by istx25** [comment] 2016-10-20 08:24
I believe this issue has been resolved.

**Closed by istx25** 2016-10-20 08:24 UTC
Labels: enhancement, help wanted
