### ISSUE TITLE
No such module [Quick|Nimble]

### ISSUE THREAD

**Issue by andrashatvani** [Quick/Quick#732] opened 2017-08-15 06:06 UTC
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?
* added Quick and Nimble to Podfile
```ruby
platform :ios, '11.0'
use_frameworks!

target 'bcHealth' do
    pod 'Kanna'
end

def testing_pods
    pod 'Quick'
    pod 'Nimble'
end

target 'bcHealthTests' do
    testing_pods
end

target 'bcHealthUITests' do
    testing_pods
end
```
* ran `pod install`
* tried to `import Quick` and `import Nimble`

### What did you expect to happen?

Modules will be imported.

### What actually happened instead?

`No such module 'Nimble'` and `No such module 'Quick'` failures have been shown.

### Environment

List the software versions you're using:

 - Quick: latest available via Cocoapods - see Podfile
 - Nimble:  latest available via Cocoapods - see Podfile
 - Xcode Version: Version 9.0 beta 5 (9M202q)
 - Swift Version: Apple Swift version 4.0 (swiftlang-900.0.59 clang-900.0.34.2)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: 1.3.1

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.0 (9M202q)
         Git : git version 2.13.3 (Apple Git-91)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 9904c0a7ff1c399257cfe95d91afba77f4cd6fc2
```

**Comment by ikesyo** [comment] 2017-08-15 08:35
Thanks for filing an issue, but this should be a duplicate of #717 and #729. See https://github.com/Quick/Quick/issues/729#issuecomment-318566338 for the details.

**Closed by ikesyo** 2017-08-15 08:35 UTC
