### ISSUE TITLE
Trying to run a specific spec does not run any tests

### ISSUE THREAD

**Issue by cooksimo** [Quick/Quick#889] opened 2019-05-13 04:16 UTC
### What did you do?

Running a spec with the play button in Xcode results in no tests being run.

### What did you expect to happen?

The specific spec to be run

### What actually happened instead?

No tests were run

### Environment

List the software versions you're using:

 - Quick: *latest from master 32804c3*
 - Nimble: *8.0.1*
 - Xcode Version: *10.2.1* (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: *Xcode Default* (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.6.1*

**Comment by ikesyo** [comment] 2019-05-13 04:33
Related to/Duplicate of #221, #534, #825.

**Closed by ikesyo** 2019-05-13 04:33 UTC

**Comment by cooksimo** [comment] 2019-05-13 05:04
Hmm, ok, this was working pre-Quick 2.0 and Xcode 10.2
