### ISSUE TITLE
[XCode9 beta1,swift4] Quick can't compile

### ISSUE THREAD

**Issue by xianbinKit** [Quick/Quick#717] opened 2017-07-06 14:07 UTC
- [ ] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Please replace this with what you did.

### What did you expect to happen?

Please replace this with what you expected to happen.

### What actually happened instead?

Please replace this with what happened instead.

### Environment

List the software versions you're using:

Installing Nimble (7.0.1)
Installing Quick (1.1.0)
 - Xcode Version: XCode Version 9.0 beta1 (9M136h)
 - Swift Version: swift4

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: 1.3.0.beta.2 (Use `pod --version` in Terminal)
 - Carthage: *?.?* (Use `carthage version` in Terminal)
 - Swift Package Manager *?.?.? (swiftpm-???)* (Use `swift build --version` in Terminal)

### Project that demonstrates the issue

when import Quick :

No such a module "Quick"

When run test Cmd + U : 
UseQuick/Pods/Quick/Sources/QuickObjectiveC/QuickSpec.m:105:38: Property 'name' not found on object of type 'Example *'
UseQuick/Pods/Quick/Sources/QuickObjectiveC/QuickSpec.m:131:22: Property 'isSharedExample' not UseQuick/Pods/Quick/Sources/QuickObjectiveC/QuickSpec.m:132:33: Property 'callsite' not found on object of type 'Example *'
UseQuick/Pods/Quick/Sources/QuickObjectiveC/QuickSpec.m:133:35: Property 'callsite' not found on object of type 'Example *'

Please link to a project we can download that reproduces the issue. Feel free
to delete this section if it's not relevant to the issue (eg - feature request).

The project should be [short, self-contained, and correct example](http://sscce.org/).

**Comment by ikesyo** [comment] 2017-07-29 07:26
This is a duplicate of #729. Closing.

**Closed by ikesyo** 2017-07-29 07:26 UTC
