### ISSUE TITLE
Quick was compiled with optimization - stepping may behave oddly; variables may not be available

### ISSUE THREAD

**Issue by onmyway133** [Quick/Quick#515] opened 2016-04-11 19:35 UTC
I got a breakpoint EXE_BAD_INSTRUCTION at

```swift
internal func it(description: String, flags: FilterFlags, file: String, line: UInt, closure: () -> ()) {
        if beforesCurrentlyExecuting {
            raiseError("'it' cannot be used inside 'beforeEach', 'it' may only be used inside 'context' or 'describe'. ")
        }
        if aftersCurrentlyExecuting {
            raiseError("'it' cannot be used inside 'afterEach', 'it' may only be used inside 'context' or 'describe'. ")
        }
        guard currentExampleMetadata == nil else {
            raiseError("'it' cannot be used inside 'it', 'it' may only be used inside 'context' or 'describe'. ")
        }
        let callsite = Callsite(file: file, line: line)
        let example = Example(description: description, callsite: callsite, flags: flags, closure: closure)
        currentExampleGroup.appendExample(example)  // GOT BREAKPOINT HERE
    }
```

This happens in my test targets, sometimes I get it, so don't know how to reproduce. Any help is appreciated 😢

**Comment by onmyway133** [comment] 2016-04-11 19:40
I'm using code like this to read fixture files

```swift
class DummySpec: QuickSpec {}

struct Helper {
  static func read(fileName: String) -> NSData {
    let path = NSBundle(forClass: DummySpec().dynamicType).pathForResource(fileName, ofType: "json")!
    return NSData(contentsOfFile: path)!
  }
  
  static func readJSON(fileName: String) -> [String: AnyObject] {
    let data = Helper.read(fileName)
    return try! NSJSONSerialization.JSONObjectWithData(data, options: .AllowFragments) as! [String: AnyObject]
  }
}
```

after changing it to

```swift
static func readJSON(fileName: String) -> [String: AnyObject] {
    let data = Helper.read(fileName)
    if let json = try? NSJSONSerialization.JSONObjectWithData(data, options: .AllowFragments),
      jsonDictionary = json as? [String: AnyObject] {
      return jsonDictionary
    } else {
      return [:]
    }
  }
```

I don't get that problem, it was probably the optional force unwrapping issue, but I check that the data is ALWAYS read successfully 🐼

**Comment by morganchen12** [comment] 2016-04-12 00:49
I don't think this is a bug on your end; this looks like it may be related to or a duplicate of #506.

**Comment by onmyway133** [comment] 2016-04-21 22:16
@morganchen12 you're right. I still get this problem, sometimes

**Comment by briancroom** [comment] 2016-04-22 01:40
@onmyway133 could you pull in the master branch of Quick and check if you still encounter this? I'm hoping that #517 will have resolved it.

**Comment by onmyway133** [comment] 2016-04-22 20:28
@briancroom It seems to work 🚀

**Comment by briancroom** [comment] 2016-04-22 20:31
:clap:

**Closed by briancroom** 2016-04-22 20:31 UTC
