### ISSUE TITLE
fdescribe, fit, fcontext stopped working.

### ISSUE THREAD

**Issue by fousa** [Quick/Quick#886] opened 2019-05-08 20:33 UTC
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I want to use `fdescribe` to make sure just on test runs.

When I use `github "Quick/Quick"` is works for an iOS test target. On tvOS I have to downgrade to `github "Quick/Quick" == 2.0`.

But when I switch to `github "Quick/Quick" "master"` it seems to be broken on both platforms.

### What did you expect to happen?

Only the tests in this file run.

### What actually happened instead?

All the tests run until I hit the tests in this file and Xcode stops the test suite.

### Environment

List the software versions you're using:

 - Quick: *2.1.0*
 - Nimble: *commit 0edb48d936f31f4ce657047884b77b6e3b0bef4b*
 - Xcode Version: *10.2.1 (10E1001)*
 - Swift Version: *Xcode Default*

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Carthage: *0.32.0* (Use `carthage version` in Terminal)

**Comment by cooksimo** [comment] 2019-05-13 04:08
I have the same issue, also trying to run a specific spec via the button in Xcode results in no tests being run

**Comment by ikesyo** [comment] 2019-05-13 04:37
[The test](https://github.com/Quick/Quick/blob/master/Tests/QuickTests/QuickFocusedTests/FocusedTests.swift) in our test suite is passing in all supported platforms (macOS, iOS, tvOS, SwiftPM on macOS, SwiftPM on Linux). It would be great if you could provide a reproducible case/project.

**Comment by ikesyo** [comment] 2019-05-13 05:19
#873 may be related.

**Comment by cooksimo** [comment] 2019-05-13 05:21
I am seeing the same issue, will see if I can come up with a sample project tomorrow.

**Comment by fousa** [comment] 2019-05-15 09:41
I tried using Quick from the master branch (after the #873 fix was merged) and the probleem seems to persist. I'll see if I can upload a sample project this weekend.

**Comment by ikesyo** [comment] 2019-05-15 11:13
I didn't say #873 may be fix for this, but said #873 may be the cause of this.

**Comment by fousa** [comment] 2019-05-15 11:28
Ah alright, my bad.

**Comment by pimnijman** [comment] 2019-11-22 13:25
Any updates on this? I'm running into this issue right now and since the last comment is from May I was hoping you found a fix.

**Comment by mikkoseppa** [comment] 2019-12-30 09:40
Okay so I spent some time trying to figure this out.

**Example setup with three specs, single test focused using `fit`:**
- QuickSpec1
  - it("TestCase1")
  - it("TestCase2")
  - it("TestCase3")
- QuickSpec2
  - fit("TestCase4")
  - it("TestCase5")
  - it("TestCase6")
- QuickSpec3
  - it("TestCase7")
  - it("TestCase8")
  - it("TestCase9")

**How it worked before: (I'm not really sure which version changed it, but I guess it's 2.1.0):**
Run tests --> only TestCase4 is executed.

**How it works now:**
Run tests --> TestCase1, TestCase2, TestCase3, TestCase4 are executed

But what is strange is, if instead I focus on TestCase1, it only runs that one and doesn't even proceed to other tests. I guess that is accidentally the case also in your [unit tests](https://github.com/Quick/Quick/blob/master/Tests/QuickTests/QuickFocusedTests/FocusedTests.swift). The focused test-cases are run first, so it stops right after those.

How it worked before is the intended behavior, right? At least that is how some other test frameworks work with test focusing.
I guess something has changed in how focused tests are discovered?

However I found out that setting `QuickConfiguration`'s `runAllWhenEverythingFiltered` to false makes the test focusing behave as before. Of course this is not a real solution, but anyone having this problem might be able to set it to false during development to focus tests.

**Comment by Ner1Co** [comment] 2020-01-14 18:11
This is the [commit](https://github.com/Quick/Quick/pull/873/commits/a3ece4f911ea2cb3423a32a7ab48aacc5e498265) () that caused the issue.
Renaming `defaultTestSuite` back to `initialize` solves it.

Didn't go deep into that, but seems that `buildExamplesIfNeeded` should be called before  `defaultTestSuite`.

Adding `initialize` back to `QuickSpec` class also solves to issue:
```objc
+ (void)initialize {
  [self buildExamplesIfNeeded];
}
```

**Comment by ikesyo** [comment] 2020-05-29 00:26
I submitted a possible fix for this issue in #980. Could you all try that branch?

**Closed** 2020-05-31 11:29 UTC
Labels: bug

**Comment by ikesyo** [comment] 2020-06-01 00:28
[v2.2.1](https://github.com/Quick/Quick/releases/tag/v2.2.1) has been released. Please try it!
