### ISSUE TITLE
XCTest.waitForExpectations() crashes on timeout in QuickSpec tests

### ISSUE THREAD

**Issue by Nooba** [Quick/Quick#951] opened 2020-03-10 11:48 UTC
- [X] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I'm trying to write some CoreData tests, and at some point I need to be able to wait for the NSManagedObjectContextDidSave notification before going further. This led me to use expectation() & waitForExpectations() from XCTest. It works when the expected notifications are received, but crashes on timeout.

### What did you expect to happen?

I expect the test to fail.

### What actually happened instead?

The test crashes with the following logs:
```
Test Case '-[QuickSpecCrashOnExpectationsTests.QuickSpecCrashOnExpectationsCrashingTest Should_timeout_the_test__yet_it_crashes]' started.
2020-03-10 12:33:59.063378+0100 QuickSpecCrashOnExpectations[57963:742549] *** Assertion failure in -[XCTestCase(Failures) _enqueueFailureWithDescription:inFile:atLine:expected:interruptTest:breakWhenDequeued:](), /Library/Caches/com.apple.xbs/Sources/XCTest_Sim/XCTest-15702/Sources/XCTestFramework/Core/XCTestCase+Failures.m:67
2020-03-10 12:33:59.064343+0100 QuickSpecCrashOnExpectations[57963:742549] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unable to report test assertion failure 'Asynchronous wait failed: Exceeded timeout of 3 seconds, with unfulfilled expectations: "Expect notification 'NSManagingContextDidSaveChangesNotification' from foo".' from /Users/siegele/Sources/QuickSpecCrashOnExpectations/QuickSpecCrashOnExpectationsTests/QuickSpecCrashOnExpectationsCrashingTest.swift:20 because it was raised inside test case -[QuickSpecCrashOnExpectationsCrashingTest (null)] which has no associated XCTestRun object. This may happen when test cases are constructed and invoked independently of standard XCTest infrastructure, or when the test has already finished.'
```

### Environment

 - Quick: 2.2.0 (7fb19e13be07b5dfb3b90d4f9824c855a11af40e)
 - Nimble: Unused
 - Xcode Version: Version 11.3.1 (11C505)
 - Swift Version: Xcode Default
 - CocoaPods: 1.9.1

### Project that demonstrates the issue

https://github.com/Nooba/QuickSpecCrashOnExpectations/tree/master/QuickSpecCrashOnExpectationsTests

QuickSpecCrashOnExpectationsWorkingTest is a regular XCTestCase failing as expected
QuickSpecCrashOnExpectationsCrashingTest is a QuickSpec test crashing instead of failing.

**Comment by ikesyo** [comment] 2020-03-29 16:25
This is a duplicate of #330. Please use `QuickSpec.current` over `self`. See also #645 for the details.

**Closed by ikesyo** 2020-03-29 16:25 UTC
