### ISSUE TITLE
Running code before each context

### ISSUE THREAD

**Issue by donnywals** [Quick/Quick#788] opened 2018-05-08 09:53 UTC
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I set up the following test:

```swift
describe("Given a login form") {
  var form: Form!

  beforeEach {
    form = Form()
  }

  context("When setting a username") {
    form.username = "Mickey"

    it("Then the form should have a username") {
        expect(form.username) == "Mickey"
    }
  }

  context("When setting a password") {
    form.password = "IAmMickey"

    it("Then the form should have a password") {
        expect(form.username) == "IAmMickey"
    }
  }
}
```

### What did you expect to happen?

I expected a new `Form` instance to be created before each context would run.

### What actually happened instead?

My suite crashed.

### Environment

List the software versions you're using:

 - Quick: 1.2.0
 - Xcode Version: 9.2
 - Swift Version: 4.0.3

### Possible solution

Would it be possible to introduce something like a `beforeEachContext` and `afterEachContext` method to accommodate a setup like the one I have shared above?

**Comment by wongzigii** [comment] 2018-05-09 07:36
AFAIK, `beforeEach` will only trigger when there is a `it` block.

See https://github.com/Quick/Quick/issues/445#issuecomment-260572143

**Comment by donnywals** [comment] 2018-05-10 04:27
Yes I am aware of that. I guess my issue mostly is that I noticed this and am looking for a way to execute something before a context runs so I can set up my code as I’ve shown in my issue (possibly adding it in a PR if folks agree this could be useful)

**Comment by VojtaStavik** [comment] 2018-12-03 09:54
I know this issue is a little bit old but I just came across it and I’d like to verify my thinking. My guess is that the suite was crashing because of `form.username = "Mickey"` not being wrapped inside in its own `beforeEach`. It caused the line being executed before the shared `beforeEach` closure in which you create the form. 

AFAIK this is intended behavior and this issue can be closed.

**Comment by donnywals** [comment] 2018-12-03 10:45
This is correct. However, what I intended to bring to light with this issue is that there is no way to run a block of code before a context block is run.

**Comment by geraldeersteling** [comment] 2020-07-13 11:43
I too thought `beforeEach` and `afterEach` would work like this. Is there a possibility that this would be implemented?

**Comment by ikesyo** [comment] 2021-05-26 15:56
https://github.com/Quick/Quick/issues/788#issuecomment-443651565 describes the situation correctly. Closing.

**Closed by ikesyo** 2021-05-26 15:56 UTC
Labels: question
